spring:
  application:
    name: Movie-ticket-booking-system
  datasource:
    url: jdbc:mysql://localhost:3306/movie-ticket-booking-system?createDatabaseIfNotExist=true
    username: root
    password: Indushree$757
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true